### ISSUE TITLE
Link in the wiki dysfunctional

### ISSUE THREAD

**Issue by galantra** [glutanimate/note-organizer#2]
Hi, [the link to ankiweb in the wiki](https://github.com/glutanimate/note-organizer#installation
) doesn't seem to work.

Greetings

**Comment by galantra** [comment]
Oh, just realized that this is probably intended as it's still in the beta stadium.

**Comment by glutanimate** [comment]
Yeah, it's a placeholder for now, but I can understand how it could be confusing. In my more recent add-ons I leave the link out completely until the add-on is actually on AnkiWeb.

Still, I do appreciate your taking the time to report this!
